#!/usr/bin/sh

#Autostart shit
pgrep -x sxhkd > /dev/null || sxhkd &

killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done
polybar &

feh --bg-fill /home/hossammenem/Pictures/bg5.jpg &
picom -f &

# remap the useless caps key
setxkbmap -option caps:swapescape &

# mosue speed
xinput set-prop 'SINOWEALTH Game Mouse' 'libinput Accel Speed' -0.5

# mouse shape
xsetroot -cursor_name left_ptr


#Workspaces shit
bspc monitor -d 1 2 3

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#bspc config single_monocle              false
#bspc config top_monocle_padding         0
#bspc config right_monocle_padding       0
#bspc config bottom_monocle_padding      0
#bspc config left_monocle_padding        0

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
